import type { Job } from "./types";

export const sampleJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    minSalary: 120000,
    maxSalary: 150000,
    details:
      "Leading frontend development for a new SaaS platform using React and TypeScript.",
    email: "careers@techcorp.com",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    applyDate: "2024-01-15",
    lastDate: "2024-02-15",
    status: "applied",
  },
  {
    id: "2",
    title: "Full Stack Engineer",
    company: "StartupXYZ",
    minSalary: 100000,
    maxSalary: 130000,
    details: "Building scalable web applications with modern technologies.",
    email: "jobs@startupxyz.io",
    skills: ["Node.js", "React", "PostgreSQL", "AWS"],
    applyDate: "2024-01-18",
    lastDate: "2024-02-20",
    status: "shortlisted",
  },
  {
    id: "3",
    title: "Backend Developer",
    company: "DataFlow Systems",
    minSalary: 110000,
    maxSalary: 140000,
    details: "Developing high-performance APIs and microservices.",
    email: "hr@dataflow.com",
    skills: ["Python", "FastAPI", "Docker", "Kubernetes"],
    applyDate: "2024-01-20",
    lastDate: "2024-02-25",
    status: "pending",
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "CloudNine Tech",
    minSalary: 115000,
    maxSalary: 145000,
    details: "Managing cloud infrastructure and CI/CD pipelines.",
    email: "talent@cloudnine.tech",
    skills: ["AWS", "Terraform", "Jenkins", "Docker"],
    applyDate: "2024-01-22",
    lastDate: "2024-03-01",
    status: "applied",
  },
  {
    id: "5",
    title: "UI/UX Designer",
    company: "DesignHub",
    minSalary: 90000,
    maxSalary: 120000,
    details: "Creating beautiful and intuitive user interfaces.",
    email: "work@designhub.co",
    skills: ["Figma", "Adobe XD", "CSS", "Prototyping"],
    applyDate: "2024-01-25",
    lastDate: "2024-02-28",
    status: "pending",
  },
  {
    id: "6",
    title: "Software Architect",
    company: "Enterprise Solutions",
    minSalary: 150000,
    maxSalary: 180000,
    details: "Designing scalable software architecture for enterprise clients.",
    email: "careers@enterprise-sol.com",
    skills: ["System Design", "Microservices", "Java", "Cloud Architecture"],
    applyDate: "2024-01-28",
    lastDate: "2024-03-05",
    status: "shortlisted",
  },
];
